server:
  port: 8921
  servlet:
    context-path: /api
spring:
  application:
    name: ymage-backend
  profiles:
    active: local
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ymage_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  # MyBatis配置
  configuration:
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    description: ymage接口文档
    email: yngcy3@gmail.com
    concat: yngcy
    version: v0.1
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yngcy.ymagebackend.controller